apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cdk-web.fullname" . }}
  labels:
    {{- include "cdk-web.selectorLabels" . | nindent 4 }}
  namespace: {{ default .Values.namespace "default" }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "cdk-web.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "cdk-web.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        env:
          {{- toYaml .Values.env | nindent 10 }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
