apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dind-pvc
  namespace: kube-ops
  labels:
    app: dind
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 5Gi
