apiVersion: v1
kind: Service
metadata:
  name: docker-dind
  namespace: kube-ops
  labels:
    app: dind
spec:
  ports:
  - name: daemon-port
    port: 2375
    targetPort: 2375
  selector:
    app: dind
