apiVersion: apps/v1
kind: Deployment
metadata:
  name: dind
  namespace: kube-ops
  labels:
    app: dind
spec:
  selector:
    matchLabels:
      app: dind
  template:
    metadata:
      labels:
        app: dind
    spec:
      containers:
      - name: dind
        image: docker:dind
        args:
        - --registry-mirror=https://qa57rb9q.mirror.aliyuncs.com  # 指定一个镜像加速地址
        env:
        - name: DOCKER_DRIVER
          value: vfs
        - name: DOCKER_HOST
          value: tcp://0.0.0.0:2375
        - name: DOCKER_TLS_CERTDIR  # 禁用 TLS （最好是不要禁用）
          value: ""
        volumeMounts:
        - name: dind-data  # 持久化 Docker 目录
          mountPath: /var/lib/docker
        ports:
        - name: daemon-port
          containerPort: 2375
        securityContext:
          privileged: true  # 设置特权模式
      volumes:
      - name: dind-data
        persistentVolumeClaim:
          claimName: dind-pvc
